### ISSUE TITLE
invalid index of a 0-dim tensor

### ISSUE THREAD

**Issue by Jakexxh** [azadis/MC-GAN#17]
When I run the model with CUP, and got this error:

Traceback (most recent call last):
  File "train.py", line 38, in <module>
    errors = model.get_current_errors()
  File "/Users/XXX/Desktop/XXX/MC-GAN/models/cGAN_model.py", line 250, in get_current_errors
    return OrderedDict([('G_GAN', self.loss_G_GAN.data[0]),
IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number`

Please change the code `return OrderedDict([('G_GAN', self.loss_G_GAN.data[0])` in line 250 of cGAN_model.py into `return OrderedDict([('G_GAN', self.loss_G_GAN.data)`

**Comment by narusevic** [comment]
@Jakexxh Have you solved this issue?

**Comment by narusevic** [comment]
https://github.com/NVIDIA/flownet2-pytorch/issues/113#issuecomment-450802359 @Jakexxh

**Comment by Jakexxh** [comment]
Yes
