### ISSUE TITLE
Quick fix - setup error on 1 GPU machine

### ISSUE THREAD

**Issue by mrmartin** [azadis/MC-GAN#3]
If you only have one GPU, the setup steps give the following error:

> cuda runtime error (38) : no CUDA-capable device is detected

Please change `CUDA_ID=1` to `CUDA_ID=0` in scripts/train_cGAN.sh

(I can make a pull request for this if the author prefers)

**Comment by azadis** [comment]
Yes, it was mentioned in a previous issue too. 
https://github.com/azadis/MC-GAN/issues/1

I've fixed it. Thanks.
