### ISSUE TITLE
How the dataset is generated

### ISSUE THREAD

**Issue by SeaOfOcean** [azadis/MC-GAN#4]
Hi, I want to train the network on my own dataset, I'd like to know how the dataset is generated. Can you share some data preparation scripts?

**Comment by azadis** [comment]
preparing each dataset is different. Please take a look at our dataset here https://people.eecs.berkeley.edu/~sazadi/MCGAN/datasets. It helps you figure out the format.

**Comment by SeaOfOcean** [comment]
I see, thanks
